language: objective-c
osx_image: xcode11

matrix:
  include:
    - env: SCHEME="WKRKit" TYPE="build"
    - env: SCHEME="WKRKitOfflineTests" TYPE="test"
    - env: SCHEME="WKRUIKit" TYPE="build"
    - env: SCHEME="WikiRacesTests" TYPE="test"
    - env: SCHEME="WikiRaces" TYPE="build"

before_install:
  - chmod +x install_swiftlint.sh
install:
  - ./install_swiftlint.sh

script:
  - "xcodebuild clean $TYPE -workspace WikiRaces.xcworkspace -scheme $SCHEME -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.0'"
