language: objective-c

osx_image: xcode9
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build -workspace WikiRaces.xcworkspace -scheme WikiRaces CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
