language: objective-c
osx_image: xcode9.2

matrix:
  include:
    - env: SCHEME="WKRKit" TYPE="test"
    - env: SCHEME="WKRKit" TYPE="build"
    - env: SCHEME="WKRUIKit" TYPE="build"
    - env: SCHEME="WikiRaces-MW" TYPE="build"

before_install:
  - chmod +x install_swiftlint.sh
install:
  - ./install_swiftlint.sh

script:
  - "xcodebuild clean $TYPE -workspace WikiRaces.xcworkspace -scheme $SCHEME -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch),OS=11.2'"