language: objective-c

osx_image: xcode9
xcode_sdk: iphonesimulator11.0

script:
- xcodebuild clean build -workspace WikiRaces.xcworkspace -scheme 'WikiRaces (Multi-Window)' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0'
