language: objective-c

osx_image: xcode9
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -workspace WikiRaces.xcworkspace -scheme WKRKit -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0'
- xcodebuild clean build -workspace WikiRaces.xcworkspace -scheme WKRUIKit -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0'
